namespace: skillpulse-dev

backend:
  image: h4kops/skillpulse-backend:5c202067a11ad455e504fd94d3fc6454c36cd34a
  replicas: 4

frontend:
  image: h4kops/skillpulse-frontend:5c202067a11ad455e504fd94d3fc6454c36cd34a
  replicas: 1

mysql:
  image: mysql:8.4

canary:
  enabled: true
  replicas: 1
  image: h4kops/skillpulse-backend:5c202067a11ad455e504fd94d3fc6454c36cd34a
