namespace: skillpulse-stg

backend:
  image: h4kops/skillpulse-backend:5c202067a11ad455e504fd94d3fc6454c36cd34a
  replicas: 1

frontend:
  image: h4kops/skillpulse-frontend:5c202067a11ad455e504fd94d3fc6454c36cd34a
  replicas: 1

mysql:
  image: mysql:8.4

canary:
  enabled: false
