namespace: skillpulse-stg

backend:
  image: h4kops/skillpulse-backend:e06e32d241d03019348d096fe55c3dacca830623
  replicas: 1

frontend:
  image: h4kops/skillpulse-frontend:e06e32d241d03019348d096fe55c3dacca830623
  replicas: 1

mysql:
  image: mysql:8.4

canary:
  enabled: false
